
#Database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/rentcar?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.open-in-view=false
server.port=8080


#For car status component
spring.main.allow-bean-definition-overriding=true
spring.task.scheduling.pool.size=1
spring.task.scheduling.shutdown.await-termination=true


#Security
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=error